base_url: "https://demowebshop.tricentis.com"
browser: "chrome"
#browser:
#  - chrome
#  - edge
#  - firefox
valid_email: "anonymous@gamil.com"
valid_password: "Anonymous@123"
invalid_email: "wronguser@gamil.com"
invalid_password: "wrongpass"

